### ISSUE TITLE
JetPack Compose

### ISSUE THREAD

**Issue by MiladFaridnia** [stevdza-san/Foody#10]
Thanks for your perfect course.
I suggest to add one course update about implementing one of your layouts with jetpack compose and provide an overview about that.
Thanks again,
Milad

**Comment by stevdza-san** [comment]
Thanks Milad, but that would be an overkill for the course, because it's primarily built on the View system itself. I may however create a video on my YouTube channel about implementing some custom UI component with Compose. :)

**Comment by MiladFaridnia** [comment]
Thanks for your answer.
It sounds fair ;)
